package top.trumeet.mipushframework.db;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

import top.trumeet.mipushframework.event.Event;
import top.trumeet.mipushframework.event.notification.NotificationInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eventDaoConfig;
    private final DaoConfig notificationInfoDaoConfig;

    private final EventDao eventDao;
    private final NotificationInfoDao notificationInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        notificationInfoDaoConfig = daoConfigMap.get(NotificationInfoDao.class).clone();
        notificationInfoDaoConfig.initIdentityScope(type);

        eventDao = new EventDao(eventDaoConfig, this);
        notificationInfoDao = new NotificationInfoDao(notificationInfoDaoConfig, this);

        registerDao(Event.class, eventDao);
        registerDao(NotificationInfo.class, notificationInfoDao);
    }
    
    public void clear() {
        eventDaoConfig.clearIdentityScope();
        notificationInfoDaoConfig.clearIdentityScope();
    }

    public EventDao getEventDao() {
        return eventDao;
    }

    public NotificationInfoDao getNotificationInfoDao() {
        return notificationInfoDao;
    }

}
