package top.trumeet.mipushframework.db;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

import top.trumeet.mipushframework.event.Event;
import top.trumeet.mipushframework.register.RegisteredApplication;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eventDaoConfig;
    private final DaoConfig registeredApplicationDaoConfig;

    private final EventDao eventDao;
    private final RegisteredApplicationDao registeredApplicationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        registeredApplicationDaoConfig = daoConfigMap.get(RegisteredApplicationDao.class).clone();
        registeredApplicationDaoConfig.initIdentityScope(type);

        eventDao = new EventDao(eventDaoConfig, this);
        registeredApplicationDao = new RegisteredApplicationDao(registeredApplicationDaoConfig, this);

        registerDao(Event.class, eventDao);
        registerDao(RegisteredApplication.class, registeredApplicationDao);
    }
    
    public void clear() {
        eventDaoConfig.clearIdentityScope();
        registeredApplicationDaoConfig.clearIdentityScope();
    }

    public EventDao getEventDao() {
        return eventDao;
    }

    public RegisteredApplicationDao getRegisteredApplicationDao() {
        return registeredApplicationDao;
    }

}
